# compare EMA to WMA discharge data, where available
# Note: underlying/raw stage data is the same, but rating curves are generated by either WMA or EMA
# 5 sites in the Flathead


library(tidyverse)
library(dygraphs)
library(fasstr)


# EMA
EMAfiles <- list.files("C:/Users/jbaldock/OneDrive - DOI/Documents/USGS/EcoDrought/EcoDrought Working/Data/Raw data/Flathead/Export2/EMA/Continuous Data")
EMAlist <- list()
for (i in 1:length(EMAfiles)) { 
  print(EMAfiles[i])
  EMAlist[[i]] <- read_csv(paste("C:/Users/jbaldock/OneDrive - DOI/Documents/USGS/EcoDrought/EcoDrought Working/Data/Raw data/Flathead/Export2/EMA/Continuous Data/", EMAfiles[i], sep = "")) %>%
    mutate(DateTime = mdy_hm(DateTime, tz = "MST"),
           site_name = gsub("EMA.csv", "", EMAfiles[i]))
}
dat_EMA <- bind_rows(EMAlist) %>% select(DateTime, GageHeightFT, DischargeCFS, site_name, DischargeReliability) %>% 
  rename(datetime = DateTime, height_EMA = GageHeightFT, flow_EMA = DischargeCFS, dr_EMA = DischargeReliability) 


# WMA
WMAfiles <- list.files("C:/Users/jbaldock/OneDrive - DOI/Documents/USGS/EcoDrought/EcoDrought Working/Data/Raw data/Flathead/Export2/WMA/Continuous Data")[c(1,3,4,6,7)]
WMAlist <- list()
for (i in 1:length(WMAfiles)) { 
  print(WMAfiles[i])
  WMAlist[[i]] <- read_csv(paste("C:/Users/jbaldock/OneDrive - DOI/Documents/USGS/EcoDrought/EcoDrought Working/Data/Raw data/Flathead/Export2/WMA/Continuous Data/", WMAfiles[i], sep = "")) %>%
    mutate(DateTime = mdy_hm(DateTime, tz = "MST"),
           site_name = gsub("WMA.csv", "", WMAfiles[i]))
}
dat_WMA <- bind_rows(WMAlist) %>% select(DateTime, GageHeightFT, DischargeCFS, site_name, DischargeReliability) %>% 
  rename(datetime = DateTime, height_WMA = GageHeightFT, flow_WMA = DischargeCFS, dr_WMA = DischargeReliability) 

unique(dat_EMA$site_name)
unique(dat_WMA$site_name)


# join
dat_comb <- dat_WMA %>% left_join(dat_EMA)
dat_comb_daily <- dat_comb %>% 
  mutate(date = date(datetime)) %>%
  group_by(site_name, date) %>% 
  summarize(height_WMA = mean(height_WMA),
            flow_WMA = mean(flow_WMA),
            dr_WMA = min(dr_WMA, na.rm = TRUE),
            height_EMA = mean(height_EMA),
            flow_EMA = mean(flow_EMA),
            dr_EMA = min(dr_EMA, na.rm = TRUE)) %>%
  mutate(flow_WMA_log = log(flow_WMA),
         flow_EMA_log = log(flow_EMA)) %>%
  ungroup()
dat_comb_daily <- fill_missing_dates(dat_comb_daily, dates = date, groups = site_name, pad_ends = FALSE)


# compare - scatterplots
# height
dat_comb_daily %>% ggplot(aes(x = height_WMA, y = height_EMA)) + geom_point() + geom_abline(slope = 1, intercept = 0, colour = "red")+ facet_wrap(~site_name, scales = "free")
# log flow
jpeg("./Data Availability/Flathead_EMA-WMA_scatter.jpg", height = 5, width = 7, res = 500, units = "in")
dat_comb_daily %>% ggplot(aes(x = flow_WMA_log, y = flow_EMA_log)) + geom_point() + geom_abline(slope = 1, intercept = 0, colour = "red")+ facet_wrap(~site_name, scales = "free")
dev.off()

# compare time series
jpeg("./Data Availability/Flathead_EMA-WMA_timeseries.jpg", height = 7, width = 9, res = 500, units = "in")
dat_comb_daily %>% 
  select(site_name, date, flow_WMA_log, flow_EMA_log) %>%
  gather(key = "source", value = "flow_log", flow_WMA_log:flow_EMA_log) %>%
  ggplot() + 
  geom_line(aes(x = date, y = flow_log, group = source, color = source)) +
  facet_wrap(~site_name, scales = "free", nrow = 5)
dev.off()


dat_comb_daily %>% filter(site_name == "BigCreekLower") %>% select(date, flow_WMA_log, flow_EMA_log) %>% dygraph() %>% dyRangeSelector() 








